"""create clinical_sessions

Revision ID: 02946217c2ea
Revises: 5bc62034fa75
Create Date: 2026-08-05 11:48:08.866342

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02946217c2ea"
down_revision: str | None = "5bc62034fa75"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinical_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("clinic_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("professional_id", sa.Uuid(), nullable=False),
        sa.Column("session_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("administrative_notes", sa.String(length=2000), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_clinical_sessions_clinic_archived",
        "clinical_sessions",
        ["clinic_id", "is_archived"],
        unique=False,
    )
    op.create_index(
        "ix_clinical_sessions_clinic_created_at",
        "clinical_sessions",
        ["clinic_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_sessions_clinic_id"), "clinical_sessions", ["clinic_id"], unique=False
    )
    op.create_index(
        "ix_clinical_sessions_clinic_patient",
        "clinical_sessions",
        ["clinic_id", "patient_id"],
        unique=False,
    )
    op.create_index(
        "ix_clinical_sessions_clinic_professional",
        "clinical_sessions",
        ["clinic_id", "professional_id"],
        unique=False,
    )
    op.create_index(
        "ix_clinical_sessions_clinic_scheduled_at",
        "clinical_sessions",
        ["clinic_id", "scheduled_at"],
        unique=False,
    )
    op.create_index(
        "ix_clinical_sessions_clinic_status",
        "clinical_sessions",
        ["clinic_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_clinical_sessions_clinic_type",
        "clinical_sessions",
        ["clinic_id", "session_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_sessions_patient_id"), "clinical_sessions", ["patient_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clinical_sessions_patient_id"), table_name="clinical_sessions")
    op.drop_index("ix_clinical_sessions_clinic_type", table_name="clinical_sessions")
    op.drop_index("ix_clinical_sessions_clinic_status", table_name="clinical_sessions")
    op.drop_index("ix_clinical_sessions_clinic_scheduled_at", table_name="clinical_sessions")
    op.drop_index("ix_clinical_sessions_clinic_professional", table_name="clinical_sessions")
    op.drop_index("ix_clinical_sessions_clinic_patient", table_name="clinical_sessions")
    op.drop_index(op.f("ix_clinical_sessions_clinic_id"), table_name="clinical_sessions")
    op.drop_index("ix_clinical_sessions_clinic_created_at", table_name="clinical_sessions")
    op.drop_index("ix_clinical_sessions_clinic_archived", table_name="clinical_sessions")
    op.drop_table("clinical_sessions")
    # ### end Alembic commands ###
